### ISSUE TITLE
CheXpert dataset tally

### ISSUE THREAD

**Issue by FuriouslyCurious** [stanfordmlgroup/stanfordmlgroup.github.io#9]
Hi @rajpurkar,

Thanks for leading the fantastic chest x-ray projects.  Opening an issue to point out tally discrepancy I observed in my downloaded ZIP dataset:

Quote from https://stanfordmlgroup.github.io/competitions/chexpert/:
`CheXpert is a large public dataset for chest radiograph interpretation, consisting of 224,316 chest radiographs of 65,240 patients.`

Upon downloading the dataset I observed `223414 train + 234 valid images (223,648 total), and 64,740 patients`. The ZIP file did not give any CRC errors and tested successfully.  

Is there an auxiliary zip file I need to download to get the remaining images?

**Comment by rajpurkar** [comment]
This would make sense! Keep in mind the hidden test set consists of 500 studies (can contain multiple images) from 500 patients!

**Comment by Kunlei-Hong** [comment]
ok,thanks

**Comment by Kunlei-Hong** [comment]
means that there ara 64740patinets in total. that's the exact number i want.
